<?php 
	echo $this->getMethod()->getTitle() . '<br/>';
	if ($this->getInfo()->getLastTransId() == '') {
		echo $this->__('Payment has not been processed yet.') . '<br/>';
	} else {
        echo  $this->__('Payment has been processed successfully.') . '<br/>';
        $comma_separated = $this->getInfo()->getCcApproval();
        if ($comma_separated != NULL) {
            list($method, $invoice, $amount, $date, $issname, $issconf) = explode("," , $comma_separated);
            echo $this->__('Invoice: %s', $this->htmlEscape($invoice)) . '<br/>';
            echo $this->__('Debit Amount: %s', $this->htmlEscape($amount).' CAD') . '<br/>';
            echo $this->__('Payment Method: %s', 'INTERAC<sup>&reg;</sup> Online') . '<br/>';
            echo $this->__('Financial Institution: %s', $this->htmlEscape($issname)) . '<br/>';
            echo $this->__('Confirmation Number: %s', $this->htmlEscape($issconf)) . '<br/>';
            echo $this->__('Transaction Date: %s', $this->htmlEscape($date)) . '<br/>';
	        }
    }
?>